// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44FojUoYoE28AM1aUKew-3hCC_iek2Xw',
    appId: '1:759146925655:web:b8fd8b3ffb5142ce71dd12',
    messagingSenderId: '759146925655',
    projectId: 'talaamapp-4a4e9',
    authDomain: 'talaamapp-4a4e9.firebaseapp.com',
    databaseURL: 'https://talaamapp-4a4e9-default-rtdb.firebaseio.com',
    storageBucket: 'talaamapp-4a4e9.appspot.com',
    measurementId: 'G-Q2PF86CMH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_RKQbBiyBNftznIsAfvLVtcy60Z4I_4E',
    appId: '1:759146925655:android:baf70cc1b2eab7e871dd12',
    messagingSenderId: '759146925655',
    projectId: 'talaamapp-4a4e9',
    databaseURL: 'https://talaamapp-4a4e9-default-rtdb.firebaseio.com',
    storageBucket: 'talaamapp-4a4e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1IY_OSrlbpIck5hfT2-GGek2oBPOX0E',
    appId: '1:759146925655:ios:35db68b455ee493671dd12',
    messagingSenderId: '759146925655',
    projectId: 'talaamapp-4a4e9',
    databaseURL: 'https://talaamapp-4a4e9-default-rtdb.firebaseio.com',
    storageBucket: 'talaamapp-4a4e9.appspot.com',
    androidClientId: '759146925655-0is7hbj0jovt6mb6upghhltfrcu0vhb9.apps.googleusercontent.com',
    iosClientId: '759146925655-tgtkq4paqe7cekqd0bf18ise64guo288.apps.googleusercontent.com',
    iosBundleId: 'com.Talaam.teacher.elmarakbeno',
  );
}
